#!/usr/bin/python3
"""Strict Raspberry Pi Imager 2.0.10 importer and FAT sanitizer."""
import base64
import binascii
import fcntl
import json
import os
import re
import shutil
import stat
import subprocess
import tempfile
from pathlib import Path

FAILURE_MARKER = Path("/etc/consolepi/generic-imager-customization-failed")
SUCCESS_MARKER = Path("/etc/consolepi/generic-imager-customization-imported")
SUCCESS_CONTENT = b"imager-2.0.10-ed25519-imported\n"
SSH_OPERATION = Path("/etc/consolepi/.generic-imager-ssh-operation")
USER_OPERATION = Path("/etc/consolepi/.generic-imager-user-operation")
USER_OPERATION_CONTENT = b"consolepi-empty-password-v1\n"
AUDIT_LOG = Path("/etc/consolepi/generic-imager-audit.jsonl")
GUARD_ACTIVATION = Path("/etc/consolepi/imager-systemd-compat")
LEGACY_CMDLINE_PLACEHOLDER = (
    b"DO NOT EDIT THIS FILE\n\n"
    b"The file you are looking for has moved to /boot/firmware/cmdline.txt\n"
)
KEY_RE = re.compile(r"ssh-ed25519 ([A-Za-z0-9+/]+={0,2})(?: ([A-Za-z0-9._@+-]{1,128}))?")
ALLOWED_ROOT = (
    re.compile(r"bcm[0-9A-Za-z._+-]*\.dtb"), re.compile(r"kernel[0-9A-Za-z._+-]*\.img"),
    re.compile(r"initramfs[0-9A-Za-z._+-]*"), re.compile(r"start[0-9A-Za-z._+-]*\.elf"),
    re.compile(r"fixup[0-9A-Za-z._+-]*\.dat"), re.compile(r"System\.map-[0-9A-Za-z._+-]+"),
    re.compile(r"config-[0-9A-Za-z._+-]+"), re.compile(r"vmlinuz-[0-9A-Za-z._+-]+"),
)
ALLOWED_EXACT = {"bootcode.bin", "cmdline.txt", "config.txt", "COPYING.linux", "LICENCE.broadcom", "issue.txt"}
STRONG_SECRET = re.compile(rb"BEGIN (?:OPENSSH|RSA|EC|DSA) PRIVATE KEY|ssh-(?:ed25519|rsa) [A-Za-z0-9+/]{20,}")
TEXT_SECRET = re.compile(r"(?im)(?:^\s*(?:password|passwd|psk|token|secret|instance-id|ssh_authorized_keys)\s*[:=]\s*\S+|\$(?:1|2[aby]?|5|6|y)\$[^\s:]{8,})")


class ImagerImportError(ValueError):
    pass


def _safe_directory(path):
    path = Path(path)
    info = path.lstat()
    if not stat.S_ISDIR(info.st_mode) or stat.S_ISLNK(info.st_mode):
        raise ImagerImportError(f"unsafe directory: {path}")
    return path


def _lexists(path):
    try:
        Path(path).lstat()
        return True
    except FileNotFoundError:
        return False


def _validated_legacy_cmdline(path, expected_uid=0, expected_gid=0):
    path = Path(path)
    try:
        before = path.lstat()
    except FileNotFoundError:
        return None
    except OSError as exc:
        raise ImagerImportError("legacy cmdline path cannot be inspected") from exc
    if (not stat.S_ISREG(before.st_mode) or stat.S_ISLNK(before.st_mode) or
            before.st_uid != expected_uid or before.st_gid != expected_gid or
            stat.S_IMODE(before.st_mode) != 0o644 or before.st_nlink != 1):
        raise ImagerImportError("legacy cmdline path is not the safe Raspberry Pi OS placeholder")
    flags = os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0) | getattr(os, "O_NONBLOCK", 0)
    try:
        descriptor = os.open(path, flags)
    except OSError as exc:
        raise ImagerImportError("legacy cmdline placeholder cannot be opened safely") from exc
    try:
        current = os.fstat(descriptor)
        if ((current.st_dev, current.st_ino) != (before.st_dev, before.st_ino) or
                not stat.S_ISREG(current.st_mode) or current.st_nlink != 1):
            raise ImagerImportError("legacy cmdline placeholder changed during validation")
        content = os.read(descriptor, len(LEGACY_CMDLINE_PLACEHOLDER) + 1)
        if content != LEGACY_CMDLINE_PLACEHOLDER:
            raise ImagerImportError("legacy cmdline placeholder content is invalid")
    finally:
        os.close(descriptor)
    return current


def validate_legacy_cmdline(path, expected_uid=0, expected_gid=0):
    """Accept only an absent path or the exact modern Raspberry Pi OS placeholder."""
    _validated_legacy_cmdline(path, expected_uid, expected_gid)
    return True


def remove_legacy_cmdline_placeholder(path, expected_uid=0, expected_gid=0):
    """Remove only the exact validated placeholder; leave an absent path absent."""
    path = Path(path)
    validated = _validated_legacy_cmdline(path, expected_uid, expected_gid)
    if validated is None:
        return False
    try:
        current = path.lstat()
    except OSError as exc:
        raise ImagerImportError("legacy cmdline placeholder changed before removal") from exc
    if (current.st_dev, current.st_ino) != (validated.st_dev, validated.st_ino):
        raise ImagerImportError("legacy cmdline placeholder changed before removal")
    path.unlink()
    try:
        path.lstat()
    except FileNotFoundError:
        return True
    raise ImagerImportError("legacy cmdline placeholder removal failed")


def _atomic_write(path, data, mode=0o600):
    path = Path(path)
    descriptor, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        os.fchmod(descriptor, mode)
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(data if isinstance(data, bytes) else data.encode())
            stream.flush(); os.fsync(stream.fileno())
        os.replace(temporary, path)
        directory = os.open(path.parent, os.O_RDONLY | os.O_DIRECTORY)
        try: os.fsync(directory)
        finally: os.close(directory)
    finally:
        try: os.unlink(temporary)
        except FileNotFoundError: pass


def mark_failure_once(marker=FAILURE_MARKER, reason="invalid Imager customization",
                      expected_uid=0, expected_gid=0):
    """Persist only the first failure; every pre-existing object is preserved."""
    marker = Path(marker)
    directory_flags = os.O_RDONLY | os.O_DIRECTORY | getattr(os, "O_NOFOLLOW", 0)
    directory_fd = os.open(marker.parent, directory_flags)
    descriptor = None
    created = False
    try:
        parent_info = os.fstat(directory_fd)
        if (parent_info.st_uid != expected_uid or parent_info.st_gid != expected_gid or
                stat.S_IMODE(parent_info.st_mode) & 0o022):
            raise ImagerImportError("failure marker directory is unsafe")
        flags = (os.O_WRONLY | os.O_CREAT | os.O_EXCL |
                 getattr(os, "O_NOFOLLOW", 0) | getattr(os, "O_NONBLOCK", 0))
        try:
            descriptor = os.open(marker.name, flags, 0o600, dir_fd=directory_fd)
        except FileExistsError:
            return False
        created = True
        os.fchown(descriptor, expected_uid, expected_gid)
        os.fchmod(descriptor, 0o600)
        data = (reason.rstrip() + "\n").encode()
        written = os.write(descriptor, data)
        if written != len(data):
            raise ImagerImportError("failure marker write was incomplete")
        os.fsync(descriptor)
        info = os.fstat(descriptor)
        if (not stat.S_ISREG(info.st_mode) or info.st_uid != expected_uid or
                info.st_gid != expected_gid or stat.S_IMODE(info.st_mode) != 0o600 or
                info.st_nlink != 1):
            raise ImagerImportError("failure marker metadata is unsafe")
        os.fsync(directory_fd)
        return True
    finally:
        if descriptor is not None:
            os.close(descriptor)
        # A partially created marker is deliberately retained as fail-closed state.
        if created:
            os.fsync(directory_fd)
        os.close(directory_fd)


AUDIT_GUARDS = {"imager_custom", "userconf"}
AUDIT_OPERATIONS = {
    "enable_ssh", "user_config", "set_hostname", "set_wlan",
    "set_wlan_country", "set_keymap", "set_timezone", "import_ssh_id", "unknown",
}
AUDIT_RESULTS = {"accepted", "rejected"}


def append_guard_audit(guard, operation, argc, result, audit_path=AUDIT_LOG,
                       expected_uid=0, expected_gid=0):
    """Append one metadata-only, durably sequenced guard event."""
    if (guard not in AUDIT_GUARDS or operation not in AUDIT_OPERATIONS or
            result not in AUDIT_RESULTS or not isinstance(argc, int) or argc < 0 or argc > 64):
        raise ImagerImportError("invalid guard audit metadata")
    audit_path = Path(audit_path)
    directory_fd = os.open(
        audit_path.parent, os.O_RDONLY | os.O_DIRECTORY | getattr(os, "O_NOFOLLOW", 0)
    )
    descriptor = None
    created = False
    try:
        parent_info = os.fstat(directory_fd)
        if (parent_info.st_uid != expected_uid or parent_info.st_gid != expected_gid or
                stat.S_IMODE(parent_info.st_mode) & 0o022):
            raise ImagerImportError("guard audit directory is unsafe")
        base_flags = (os.O_RDWR | os.O_APPEND | getattr(os, "O_NOFOLLOW", 0) |
                      getattr(os, "O_NONBLOCK", 0))
        try:
            descriptor = os.open(audit_path.name, base_flags | os.O_CREAT | os.O_EXCL,
                                 0o600, dir_fd=directory_fd)
            created = True
        except FileExistsError:
            descriptor = os.open(audit_path.name, base_flags, dir_fd=directory_fd)
        fcntl.flock(descriptor, fcntl.LOCK_EX)
        info = os.fstat(descriptor)
        if created:
            os.fchown(descriptor, expected_uid, expected_gid)
            os.fchmod(descriptor, 0o600)
            info = os.fstat(descriptor)
        if (not stat.S_ISREG(info.st_mode) or info.st_uid != expected_uid or
                info.st_gid != expected_gid or stat.S_IMODE(info.st_mode) != 0o600 or
                info.st_nlink != 1 or info.st_size > 65536):
            raise ImagerImportError("guard audit path is unsafe")
        os.lseek(descriptor, 0, os.SEEK_SET)
        content = os.read(descriptor, 65537)
        if len(content) > 65536:
            raise ImagerImportError("guard audit is too large")
        sequence = 0
        if content:
            if not content.endswith(b"\n"):
                raise ImagerImportError("guard audit is malformed")
            for raw in content.splitlines():
                try:
                    event = json.loads(raw)
                except (UnicodeDecodeError, json.JSONDecodeError) as exc:
                    raise ImagerImportError("guard audit is malformed") from exc
                sequence += 1
                if (not isinstance(event, dict) or set(event) != {"seq", "guard", "operation", "argc", "result"} or
                        event["seq"] != sequence or event["guard"] not in AUDIT_GUARDS or
                        event["operation"] not in AUDIT_OPERATIONS or event["result"] not in AUDIT_RESULTS or
                        not isinstance(event["argc"], int)):
                    raise ImagerImportError("guard audit sequence or schema is invalid")
        event = {"seq": sequence + 1, "guard": guard, "operation": operation,
                 "argc": argc, "result": result}
        line = (json.dumps(event, separators=(",", ":")) + "\n").encode()
        if os.write(descriptor, line) != len(line):
            raise ImagerImportError("guard audit append was incomplete")
        os.fsync(descriptor)
        os.fsync(directory_fd)
        return event
    except OSError as exc:
        raise ImagerImportError("guard audit cannot be written safely") from exc
    finally:
        if descriptor is not None:
            os.close(descriptor)
        os.close(directory_fd)


def generic_pending(state="/etc/consolepi/generic-image.json"):
    """Return true only for the strict generic state in which Imager may run."""
    path = Path(state)
    try:
        info = path.lstat()
        data = path.read_bytes()
    except OSError:
        return False
    return (stat.S_ISREG(info.st_mode) and not stat.S_ISLNK(info.st_mode) and
            info.st_uid == 0 and info.st_gid == 0 and info.st_nlink == 1 and
            stat.S_IMODE(info.st_mode) == 0o600 and
            data == b'{"state":"pending"}\n')


def generic_guard_active(marker=GUARD_ACTIVATION):
    """Any object at the generic activation path prevents vendor fallback."""
    return _lexists(marker)


def record_operation(path, content):
    path = Path(path)
    if _lexists(path):
        raise ImagerImportError("Imager operation was attempted more than once")
    _atomic_write(path, content, 0o600)


def read_strict_marker(path, expected=None, expected_uid=0, expected_gid=0):
    path = Path(path)
    flags = os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0) | getattr(os, "O_NONBLOCK", 0)
    try:
        descriptor = os.open(path, flags)
    except OSError as exc:
        raise ImagerImportError(f"required marker is missing or unsafe: {path.name}") from exc
    try:
        info = os.fstat(descriptor)
        if (not stat.S_ISREG(info.st_mode) or info.st_uid != expected_uid or
                info.st_gid != expected_gid or stat.S_IMODE(info.st_mode) != 0o600 or
                info.st_nlink != 1):
            raise ImagerImportError(f"marker metadata is invalid: {path.name}")
        limit = (len(expected) if expected is not None else 8192) + 1
        data = os.read(descriptor, limit)
        if expected is not None and data != expected:
            raise ImagerImportError(f"marker content is invalid: {path.name}")
        return data
    finally:
        os.close(descriptor)


def validate_optional_marker(path, expected, expected_uid=0, expected_gid=0):
    if not _lexists(path):
        return False
    read_strict_marker(path, expected, expected_uid, expected_gid)
    return True


def ensure_transaction_open(failure_marker=FAILURE_MARKER, success_marker=SUCCESS_MARKER,
                            expected_uid=0, expected_gid=0):
    if _lexists(failure_marker):
        raise ImagerImportError("previous Imager failure marker is present")
    if _lexists(success_marker):
        mark_failure_once(failure_marker, "unexpected Imager success marker is already present",
                          expected_uid, expected_gid)
        raise ImagerImportError("unexpected Imager success marker is already present")
    return True


def guard_operation_label(mode, arguments):
    if mode == "user":
        return "user_config"
    candidate = arguments[0] if arguments else "unknown"
    return candidate if candidate in AUDIT_OPERATIONS and candidate != "user_config" else "unknown"


def validate_userconf_request(arguments):
    if list(arguments) != ["consolepi", ""]:
        raise ImagerImportError("generic image rejects username or password customization")
    return True


def validate_ssh_request(arguments):
    arguments = list(arguments)
    if len(arguments) != 3 or arguments[:2] != ["enable_ssh", "-k"]:
        raise ImagerImportError("generic image permits only enable_ssh -k")
    return validate_ed25519_key(arguments[2])


def require_no_host_keys(directory="/etc/ssh"):
    if next(Path(directory).glob("ssh_host_*"), None) is not None:
        raise ImagerImportError("SSH host identity exists before generic first boot")
    return True


def validate_host_keys(directory="/etc/ssh", expected_uid=0, expected_gid=0):
    directory = Path(directory)
    private = sorted(path for path in directory.glob("ssh_host_*_key")
                     if not path.name.endswith(".pub"))
    if not private:
        raise ImagerImportError("SSH host keys were not generated")
    expected_paths = {path for key in private for path in (key, Path(str(key) + ".pub"))}
    if set(directory.glob("ssh_host_*")) != expected_paths:
        raise ImagerImportError("unexpected SSH host identity file exists")
    for key in private:
        public = Path(str(key) + ".pub")
        for path, mode in ((key, 0o600), (public, 0o644)):
            try:
                info = path.lstat()
            except OSError as exc:
                raise ImagerImportError("SSH host key pair is incomplete") from exc
            if (not stat.S_ISREG(info.st_mode) or stat.S_ISLNK(info.st_mode) or
                    info.st_uid != expected_uid or info.st_gid != expected_gid or
                    info.st_nlink != 1 or stat.S_IMODE(info.st_mode) != mode):
                raise ImagerImportError("SSH host key metadata is unsafe")
        if subprocess.run(["ssh-keygen", "-lf", str(public)], stdout=subprocess.DEVNULL,
                          stderr=subprocess.DEVNULL).returncode:
            raise ImagerImportError("SSH host public key is invalid")
    return True


def provision_host_keys(directory="/etc/ssh", expected_uid=0, expected_gid=0,
                        command_runner=subprocess.run):
    require_no_host_keys(directory)
    generated = command_runner(["ssh-keygen", "-A"], stdout=subprocess.DEVNULL,
                               stderr=subprocess.DEVNULL)
    if generated.returncode:
        raise ImagerImportError("ssh-keygen -A failed")
    validate_host_keys(directory, expected_uid, expected_gid)
    checked = command_runner(["sshd", "-t"], stdout=subprocess.DEVNULL,
                             stderr=subprocess.DEVNULL)
    if checked.returncode:
        raise ImagerImportError("sshd -t failed")
    return True


def restore_vendor_entrypoint(active, backup, expected_wrapper,
                              expected_uid=0, expected_gid=0):
    """Replace an activated guard with its preserved vendor implementation."""
    active, backup, expected_wrapper = map(Path, (active, backup, expected_wrapper))
    expected = expected_wrapper.read_bytes()
    for path, wrapper in ((active, True), (backup, False)):
        info = path.lstat()
        if (not stat.S_ISREG(info.st_mode) or stat.S_ISLNK(info.st_mode) or
                info.st_uid != expected_uid or info.st_gid != expected_gid or
                info.st_nlink != 1 or stat.S_IMODE(info.st_mode) & 0o022):
            raise ImagerImportError("Imager vendor entrypoint metadata is unsafe")
        if wrapper and path.read_bytes() != expected:
            raise ImagerImportError("activated Imager guard was modified")
    os.replace(backup, active)
    directory = os.open(active.parent, os.O_RDONLY | os.O_DIRECTORY)
    try:
        os.fsync(directory)
    finally:
        os.close(directory)


def validate_imager_markers(failure_marker=FAILURE_MARKER, success_marker=SUCCESS_MARKER,
                            expected_uid=0, expected_gid=0):
    failure_marker, success_marker = Path(failure_marker), Path(success_marker)
    try:
        failure_marker.lstat()
    except FileNotFoundError:
        pass
    except OSError as exc:
        raise ImagerImportError("failure marker cannot be inspected") from exc
    else:
        raise ImagerImportError("Imager customization failure marker is present")
    flags = os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0)
    try:
        descriptor = os.open(success_marker, flags)
    except OSError as exc:
        raise ImagerImportError("success marker is missing or unsafe") from exc
    try:
        info = os.fstat(descriptor)
        if (not stat.S_ISREG(info.st_mode) or info.st_uid != expected_uid or
                info.st_gid != expected_gid or stat.S_IMODE(info.st_mode) != 0o600 or
                info.st_nlink != 1):
            raise ImagerImportError("success marker metadata is invalid")
        content = os.read(descriptor, len(SUCCESS_CONTENT) + 1)
        if content != SUCCESS_CONTENT:
            raise ImagerImportError("success marker content is invalid")
    finally:
        os.close(descriptor)
    return True


def validate_ed25519_key(key):
    match = KEY_RE.fullmatch(key)
    if not match:
        raise ImagerImportError("expected exactly one unoptioned Ed25519 key")
    try:
        blob = base64.b64decode(match.group(1), validate=True)
    except (binascii.Error, ValueError) as exc:
        raise ImagerImportError("invalid Ed25519 key encoding") from exc
    if len(blob) != 51 or blob[:4] != b"\x00\x00\x00\x0b" or blob[4:15] != b"ssh-ed25519" or blob[15:19] != b"\x00\x00\x00\x20":
        raise ImagerImportError("invalid Ed25519 wire-format key")
    return key


def install_authorized_key(home, uid, gid, key):
    home = _safe_directory(home)
    if home.stat().st_uid != uid:
        raise ImagerImportError("consolepi home has an unexpected owner")
    home_fd = os.open(home, os.O_RDONLY | os.O_DIRECTORY | getattr(os, "O_NOFOLLOW", 0))
    try:
        home_info = os.fstat(home_fd)
        if home_info.st_uid != uid or not stat.S_ISDIR(home_info.st_mode):
            raise ImagerImportError("consolepi home changed during import")
        created = False
        try:
            os.mkdir(".ssh", 0o700, dir_fd=home_fd)
            created = True
        except FileExistsError: pass
        ssh_fd = os.open(".ssh", os.O_RDONLY | os.O_DIRECTORY | getattr(os, "O_NOFOLLOW", 0), dir_fd=home_fd)
        try:
            if created:
                os.fchown(ssh_fd, uid, gid)
            info = os.fstat(ssh_fd)
            if info.st_uid != uid:
                raise ImagerImportError(".ssh has an unexpected owner")
            os.fchmod(ssh_fd, 0o700)
            try: os.stat("authorized_keys", dir_fd=ssh_fd, follow_symlinks=False)
            except FileNotFoundError: pass
            else: raise ImagerImportError("authorized_keys already exists")
            name = f".authorized_keys.{os.getpid()}.new"
            flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0)
            descriptor = os.open(name, flags, 0o600, dir_fd=ssh_fd)
            try:
                os.write(descriptor, (key + "\n").encode()); os.fsync(descriptor)
                os.fchmod(descriptor, 0o600); os.fchown(descriptor, uid, gid)
            finally: os.close(descriptor)
            os.rename(name, "authorized_keys", src_dir_fd=ssh_fd, dst_dir_fd=ssh_fd)
            os.fsync(ssh_fd)
        finally: os.close(ssh_fd)
    finally: os.close(home_fd)


def cleanup_imager_payload(boot_mount):
    root = _safe_directory(boot_mount)
    payload = root / "firstrun.sh"
    payload.unlink(missing_ok=True)
    if payload.exists() or payload.is_symlink():
        raise ImagerImportError("cannot remove Imager payload")
    directory = os.open(root, os.O_RDONLY | os.O_DIRECTORY)
    try: os.fsync(directory)
    finally: os.close(directory)
    cmdline = root / "cmdline.txt"
    if cmdline.is_symlink() or not cmdline.is_file():
        raise ImagerImportError("missing or unsafe cmdline.txt")
    lines = cmdline.read_text().splitlines()
    if len(lines) != 1: raise ImagerImportError("cmdline.txt is malformed")
    denied = ("systemd.run=", "systemd.run_success_action=", "systemd.run_failure_action=", "ds=nocloud")
    tokens = [x for x in lines[0].split() if not x.startswith(denied) and x != "systemd.unit=kernel-command-line.target"]
    _atomic_write(cmdline, " ".join(tokens) + "\n", 0o644)


def clear_directory(path):
    root = _safe_directory(path)
    for entry in os.scandir(root):
        candidate = Path(entry.path)
        shutil.rmtree(candidate) if entry.is_dir(follow_symlinks=False) else candidate.unlink()


def _allowed_boot_entry(path):
    if path.name in ALLOWED_EXACT: return True
    if path.name == "overlays" and path.is_dir() and not path.is_symlink(): return True
    return any(pattern.fullmatch(path.name) for pattern in ALLOWED_ROOT)


def scan_boot_partition(path):
    root = _safe_directory(path)
    for candidate in root.rglob("*"):
        if candidate.is_symlink(): raise ImagerImportError(f"boot symlink is not allowed: {candidate.name}")
        if not candidate.is_file(): continue
        data = candidate.read_bytes()
        if STRONG_SECRET.search(data): raise ImagerImportError(f"credential material remains in {candidate.name}")
        if len(data) <= 1024 * 1024 and b"\x00" not in data:
            try: text = data.decode("utf-8")
            except UnicodeDecodeError: continue
            if TEXT_SECRET.search(text): raise ImagerImportError(f"provisioning data remains in {candidate.name}")


def sanitize_boot_partition(path):
    root = _safe_directory(path)
    for entry in list(root.iterdir()):
        if not _allowed_boot_entry(entry):
            shutil.rmtree(entry) if entry.is_dir() and not entry.is_symlink() else entry.unlink()
    overlays = root / "overlays"
    if overlays.exists():
        for entry in list(overlays.iterdir()):
            if entry.is_symlink() or not (entry.is_file() and (entry.suffix in {".dtbo", ".dtb"} or entry.name == "README")):
                shutil.rmtree(entry) if entry.is_dir() and not entry.is_symlink() else entry.unlink()
    for required in (root / "config.txt", root / "cmdline.txt"):
        if required.is_symlink() or not required.is_file(): raise ImagerImportError(f"required boot file missing: {required.name}")
    cleanup_imager_payload(root)
    scan_boot_partition(root)
