# SSH_PORT|DEVICE_NAME|SERIAL_DEVICE
2201|KONZOLE-1|/dev/consolepi/unassigned-1
2202|KONZOLE-2|/dev/consolepi/unassigned-2
2203|KONZOLE-3|/dev/consolepi/unassigned-3
2204|KONZOLE-4|/dev/consolepi/unassigned-4
